- helm_deploy/crime-portal-gateway/templates/_envs.tpl
Next step towards getting deploy dev stage to work. Have also added the secret into the crime-portal-mirror-gateway-dev  namespace.
> Pic 847 update helm deploy

- .circleci/config.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/health/PingTest.kt
We need to improve the message. I have raised a support issue to help progress but don't want to block our further development
> Pic 847 slack integration

- README.md
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/config/SoapHeaderAddressInterceptor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/config/WebServiceConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/LocalDateTimeAdapter.kt
- src/main/resources/xsd/binding.xjb
- src/main/resources/xsd/cp/AuditActions.xsd
- src/main/resources/xsd/cp/CSCI.xsd
- src/main/resources/xsd/cp/CSCI_Body.xsd
- src/main/resources/xsd/cp/External/ExternalDocumentRequest.xsd
- src/main/resources/xsd/cp/External/StandardCourtList.xsd
- src/main/resources/xsd/cp/GatewayMessageSchema.xsd
- src/main/resources/xsd/generic/Acknowledgement/Acknowledgement.xsd
- src/main/resources/xsd/generic/CSCI_Header.xsd
- src/main/resources/xsd/generic/CSCI_Status.xsd
- src/main/resources/xsd/generic/SchemaHeader.xsd
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/config/SoapHeaderAddressInterceptorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/LocalDateTimeAdapterTest.kt
- src/test/resources/sample-soap-request.xml
Highlights
1. XSD loaded as the contract. generation of Java sources via gradle plugin
2. Endpoint handles the payload
3. Interceptor handles the SOAP header values
> ✨ PIC-849 Add Kotlin endpoint to receive the ExternalDocumentRequest

- .editorconfig
- build.gradle.kts
- docker-compose.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/CrimePortalGateway.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/AwsConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/CrimePortalGatewayExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/MessagingConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/SoapHeaderAddressInterceptor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/TelemetryConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/health/HealthInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/health/VersionOutputter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/SqsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/TelemetryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/LocalDateTimeAdapter.kt
- src/main/resources/application-dev.yml
- src/main/resources/xsd/cp/external/ExternalDocumentRequest.xsd
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/MessagingConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/SoapHeaderAddressInterceptorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/healthchecks/SqsCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/health/HealthInfoTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/health/HealthCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/health/InfoTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/SqsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/LocalDateTimeAdapterTest.kt
> Add standard court list xsd

- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointIntTest.kt
- src/test/resources/application-test.yml
- src/test/resources/sample-soap-request.xml
Small one - ensure that payload is not validated and that a SOAP fault is returned
> ✨PIC-895 SOAP fault

- docker-compose.yml
- helm_deploy/crime-portal-gateway/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceSecurityConfig.kt
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
> Pic 979 fix security

- build.gradle.kts
This version uses v2 of the AI Agent rather than v3 which had issues
> ⬆️ Use latest version of dps plugin

- .circleci/config.yml
This reverts commit 52a5ece773aa32318a39f80f9f151e0b1727f471.
> Revert "💚 Distinguish Jira CI token to prevent conflict"

- .gitignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/resources/application.yml
Also sorted the courts for easier comparison in the future. Trace log on the message in case we have to debug further requests.
> Pic 850 debug court code

- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
Only changes the log level in 3 places
> Reduce redundant info level logging

- helm_deploy/crime-portal-gateway/templates/ingress.yaml
For pen test. No need for this to go as far as prod - just preprod
> 🔧 PIC-1046 remove modsec

- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/DocumentUtils.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/DocumentUtilsTest.kt
- src/test/resources/external-document-request/request-B10JQ01.xml
Any messages indicating a court room > 50 (min-dummy-court-room property) will be ignored and not placed on the SQS queue
> ✨ PIC-1103 filter out messages for dummy courts

- Dockerfile
- build.gradle.kts
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/WebServiceSecurityConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/main/resources/xsd/cp/GatewayMessageSchema.xsd
- src/main/resources/xsd/cp/external/ExternalDocumentRequest.xsd
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointIntTest.kt
Fix required new change of alias and Acknowledgement in a separate namespace from ExternalDocumentRequest
> Pic 1099 cgi response

- build.gradle.kts
Simple upgrade of spring boot via gradle parent
> Security advisory

- README.md
- build.gradle.kts
- docker-compose.yml
- helm_deploy/crime-portal-gateway/templates/_envs.tpl
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/AwsConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpoint.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/S3Service.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/DocumentUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/MessageDetail.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/MessagingConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/endpoint/ExternalDocRequestEndpointTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/integration/endpoint/ExternalDocRequestEndpointIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/S3ServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/MessageDetailTest.kt
- src/test/resources/application-test.yml
- src/test/resources/localstack/setup-s3.sh
Store all messages that we receive in the gateway to S3 bucket. For purposes of debugging, etc.
> ✨ PIC-1319 back up raw payloads to S3 bucket

- helm_deploy/crime-portal-gateway/templates/_envs.tpl
> ✨ PIC-1319 fix bucket_name and bucket_arn

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
This is the same as prod now. Pankaj noticed that WSDL was not working on dev and pre-prod
> 🔧 PIC-1525 fix path on ingress

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
added rewrite_target to dev and pre-prod so that CGI can hit the endpoints without changing them.
> 🔧 PIC-1543 add rewrite target paths

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/MessageDetail.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/application/SoapHeaderAddressInterceptorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/service/S3ServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/crimeportalgateway/xml/MessageDetailTest.kt
> 🐞PIC-1710-fix-filename

- build.gradle.kts
spring boot new version comes through dps parent
> ⬆ upgrade deps to remove vulnerability

- helm_deploy/crime-portal-gateway/templates/deployment.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Reverts ministryofjustice/crime-portal-gateway#190
> Revert "PIC-4117 Update location of Keystore in PreProd"

- .gitignore
- helm_deploy/crime-portal-gateway/values.yaml
not facilitated by generic-service any more, but easy enough to do with plain helm
> Pic 4149 manually mount secrets

- helm_deploy/crime-portal-gateway/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Fix indenting issues when setting up generic-prometheus-alerts
> PIC-4148 Fix indenting issues

- build.gradle.kts
mockito-core is brought in by one of the other dependencies
> Remove duplicated dependency mockito test implementation

- README.md
Just needed to force a re-read of the secrets
> PIC-4625: Updates README.md
